@startuml

actor cliente

ACTIVATE InterfazPedido

cliente -> InterfazPedido : 1. Realizar pedido

InterfazPedido -> ControladorPedido: 1.1 Iniciar pedido

ACTIVATE ControladorPedido

ControladorPedido -> ControladorProductos : 1.1.2 Consultar productos existentes

ACTIVATE ControladorProductos

ControladorProductos --> ControladorPedido : 1.1.3 Listar Productos

cliente -> InterfazPedido : 2. Seleccionar Producto

InterfazPedido -> ControladorProductos : 2.1 Notifica selección del producto

ACTIVATE InfoProductos

ControladorProductos -> InfoProductos : 2.1.1 Consulta datos del producto

InfoProductos -->  ControladorProductos : 2.1.2 Devuelve lista de productos

DESTROY InfoProductos

ControladorProductos --> InterfazPedido : 2.1.3 Mostrar datos producto

cliente -> InterfazPedido : 3. Confirmar producto

InterfazPedido -> ControladorProductos : 3.1 Consultar si el producto sigue disponible

ControladorProductos --> ControladorProductos : 3.1.2 Marca el producto como comprado

ACTIVATE InfoPedido

ControladorProductos -> InfoPedido :  3.2 Añadir producto al pedido

cliente -> InterfazPedido : 4.A Seguir comprando (vuelve al paso 1.1.2)

cliente -> InterfazPedido : 4.B Terminar de comprar

InterfazPedido -> ControladorPedido : 4B.1 Notifica el final de la compra

ControladorPedido -> InfoPedido : 4B.1.1 Consulta datos del pedido

InfoPedido --> ControladorPedido : 4B.1.2 Devuelve info del pedido

DESTROY InfoPedido

ControladorPedido -> InterfazPedido : 4B.1.3 Muestra datos del pedido

cliente -> InterfazPedido : 5. Confirmar compra

cliente -> InterfazPedido : 6.Seleccionar modo de pago

cliente -> InterfazPedido : 7.Introducir datos

ACTIVATE ControladorPago

InterfazPedido -> ControladorPago : 7.1 Consulta datos cliente

ControladorPago -> InterfazBanco : 7.1.1 Consulta datos cliente

actor banco

ACTIVATE InterfazBanco

InterfazBanco -> banco : 7.1.2 Consulta datos cliente

banco --> InterfazBanco : 7.1.3 Confirma datos cliente

InterfazBanco --> ControladorPago : 7.1.4 Confirma datos cliente

ControladorPago -> InterfazBanco : 7.2 Realizar pago

InterfazBanco -> banco : 7.2.3 Realiza pago

ACTIVATE InfoPago

banco -> InfoPago : 7.2.4 Registra pago

InfoPago --> banco : 7.2.5 Confirma pago y devuelve datos

DESTROY InfoPago

banco --> InterfazBanco : 7.2.6 Confirma pago y devuelve datos

InterfazBanco --> ControladorPago : 7.2.6 Confirma pago y devuelve datos

DESTROY InterfazBanco

ControladorPago --> ControladorPedido : 7.2.7 Confirma pago y devuelve datos

DESTROY ControladorPago

ControladorPedido -> ControladorProductos : 7.3 Confirma productos como vendidos

ControladorProductos --> ControladorProductos : 7.3.1 Marca productos como vendidos

DESTROY ControladorProductos

ControladorPedido --> InterfazPedido : 7.4 Envía factura con datos de la compra

DESTROY ControladorPedido

DESTROY InterfazPedido

@enduml